export const FETCH_SITEDESIGNS = "FETCH/SITEDESIGNS";
export const FETCH_SITESCRIPTS = "FETCH/SITESCRIPTS";
export const FETCH_SITEDESIGNSANDSCRIPTS = "FETCH/SITEDESIGNSANDSCRIPTS";
export const EDIT_SITEDESIGN = "EDIT/SITEDESIGN";
export const SAVE_SITEDESIGN = "SAVE/SITEDESIGN";
export const APP_LOADING = "APP/LOADING";