export const FETCH_SITEDESIGNS = "FETCH/SITEDESIGNS";
export const FETCH_SITESCRIPTS = "FETCH/SITESCRIPTS";
export const FETCH_SITEDESIGNSANDSCRIPTS = "FETCH/SITEDESIGNSANDSCRIPTS";
export const DELETED_SITEDESIGN = "DELETED/SITEDESIGN";
export const CREATED_SITEDESIGN = "CREATED/SITEDESIGN";
export const UPDATE_SITEDESIGN = "UPDATE/SITEDESIGN";
export const SAVE_SITEDESIGN = "SAVE/SITEDESIGN";
export const APP_LOADING = "APP/LOADING";